export interface PokemonInfo {
  abilities: object[],
  base_experience: number,
  forms: { name: string, url: string }[],
  game_indices: object[],
  height: number,
  held_items: any[],
  id: number,
  is_default: boolean,
  location_area_encounters: string,
  moves: { name: string, url: string }[],
  name: string,
  order: number,
  past_types: any[],
  species: { name: string, url: string }[],
  sprites: object,
  stats: object[],
  types: object[],
  weight: number,
}
